# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               <img src="http://becc.github.io/public/logo.png"> becc
tagline:             'digital security simply'
description:         'Dedicated to helping customers build the simplest controls to make them the most secure.'
url:                 http://blog.becc.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Becc
  url:               http://blog.becc.io
  email:             info@becc.io

# Custom vars
version:             1.0.0
